# Generated by Django 6.0.6 on 2026-07-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
